### ISSUE TITLE
[Request] Resource pack root starting at the repository root 

### ISSUE THREAD

**Issue by bangetto** [OffsetMods538/Github-Resourcepack-Manager#1]
Please add an option to make it so the pack doesn't need to be in the `packs` folder and make it also so if there's a `pack.mcmeta` file in the rep root the mod no longer scans for other packs

**Comment by OffsetMonkey538** [comment]
Why would this be needed? Couldn't you just put everything in the `0-base` pack? That should work I'm pretty sure

**Comment by bangetto** [comment]
yeah, but pushing changes would be easier, because it would be possible to push it straight up from the respack folder instead of having it copied over to an another folder

**Comment by OffsetMonkey538** [comment]
Ah, that makes sense. I'll make it check if a `pack.mcmeta` file exists and `packs` folder doesn't and use the root as the pack in that case

**Comment by OffsetMonkey538** [comment]
Should be fixed in version 2.1.0

**Comment by bangetto** [comment]
thx

**Comment by OffsetMonkey538** [comment]
If you encounter any problems, you can chat with me on my [discord](https://discord.offsetmonkey538.top) :D
