### ISSUE TITLE
Send updated resourcepack to logged in clients

### ISSUE THREAD

**Issue by HoldYourWaffle** [OffsetMods538/Github-Resourcepack-Manager#3]
I'm not able to test this right now, but based on [this piece of code](https://github.com/42atomys/fabric-resourcepack-refresher/blob/3caabd76999005976ffe0d2f98f208221a61dcfa/src/main/java/codes/atomys/resourcepackrefresher/ResourcePackRefresher.java#L132-L140) from a similar mod it seems to be possible to send updated resourcepacks to logged in clients.

Could be a cool feature, though perhaps behind a config flag or command to limit the intrusiveness.

**Comment by OffsetMonkey538** [comment]
yeah I know

**Comment by OffsetMonkey538** [comment]
I've already made it work locally. stuff is planned, I'm busy

**Comment by OffsetMonkey538** [comment]
fixed by #6
