### ISSUE TITLE
1.21.4 Update

### ISSUE THREAD

**Issue by Craemon** [OffsetMods538/Github-Resourcepack-Manager#7]
Hey, would it be possible to update the mod to 1.21.4? Don't mean to bother you, would be really nice though:)
Currently just starting to mod so this seems a bit out of my league to try and attempt myself...
In any case: Thank you very much for considering, love the mod:)

**Comment by OffsetMonkey538** [comment]
Iirc there aren't any changes needed to run the mod on 1.21.4. Did you try running it? If so then was there any crash/error or did something just not work? If you haven't tried then go ahead and do it, the fabric.mod.json should only require versions above or equal to 1.19.2

Please do let me know if there are any issues or if it works perfectly fine, then I can mark 1.21.4 as supported on the modrinth page

**Comment by Craemon** [comment]
Yeah, you're right, should have done that first. I just assumed there would be a lot broken but now that I think about it most of the code is probably not even directly depending on Minecraft mechanics? I will try it out and let you know:)

**Comment by OffsetMonkey538** [comment]
Yup, pretty sure that the only things dependant on Minecraft are a mixin to run everything on the same webserver (so no need to like add another port and stuff), modifying the server.properties file and reloading it at runtime and also formatting and sending the chat message

**Comment by OffsetMonkey538** [comment]
That makes me think... Probably not that hard to port this to work on paper servers as well? Might take a look at that in the far future

**Comment by Craemon** [comment]
Oh yeah, this sounds like an ideal scenario when doing multiple loaders. Btw thank you for responding so quick.

**Comment by OffsetMonkey538** [comment]
One of the first notifications I saw when I woke up haha

**Comment by OffsetMonkey538** [comment]
So from what I understand, it should already work on 1.21.4
